### ISSUE TITLE
Asynchronous saving of the map

### ISSUE THREAD

**Issue by allesblinkt** [allesblinkt/riverbed-vision#10]
Let's try to save the map while the machine is moving. This could be a thread that will be joined after the move. This will reduce the apparent _thinking..._ time of the machine.

**Comment by prusnak** [comment]
Implemented and pushed to `async` branch.

I have not tested it, but it should work as intended, hopefully.

**Comment by allesblinkt** [comment]
Cool, thank you.

thank you. What do you think, do we run into troubles when we are
modifiying the map/stage/stones while saving? Couldn't this lead to
corrupt data?

B

**Comment by prusnak** [comment]
Good catch! I changed order execution, so thread is joined before any modification of the map structure. It is not modified anywhere outside of this loop, so I guess now it is correct and we don't need to use mutex locks: https://github.com/allesblinkt/riverbed-vision/commit/498b218862ee58e74613c9e39487e8bc1c0e854c

**Comment by prusnak** [comment]
Implemented in:
https://github.com/allesblinkt/riverbed-vision/commit/8081bfe58433ed1d4f2e4e382ebaeb6d94ecf10b
https://github.com/allesblinkt/riverbed-vision/commit/498b218862ee58e74613c9e39487e8bc1c0e854c
https://github.com/allesblinkt/riverbed-vision/commit/ee72c77b595181e55e9d8a7eb0ce0c20c20090a3
https://github.com/allesblinkt/riverbed-vision/commit/46379695a0d3f59453e256b0a7a91a9f1bb56260
https://github.com/allesblinkt/riverbed-vision/commit/d055276a5d54719ffe4ee79c93d364974ee7c474
https://github.com/allesblinkt/riverbed-vision/commit/94faf5e3382254f9f48503e66a6c94ba54be8b72
